// src/constants/ErrorCode.ts
export const ErrorCode = {
    USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
    WEAK_PASSWORD: "WEAK_PASSWORD",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",
    INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
    VERIFICATION_CODE_EXPIRED: "VERIFICATION_CODE_EXPIRED",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    INVALID_TOKEN: "INVALID_TOKEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DEFAULT: "DEFAULT",
} as const;

export type ErrorCodeType = keyof typeof ErrorCode;
