export enum NotificationType {
    DEADLINE_REMINDER = "DEADLINE_REMINDER",
    LESSON_COMPLETED = "LESSON_COMPLETED",
    LEARNING_PATH_COMPLETED = "LEARNING_PATH_COMPLETED",
    POST_LIKED = "POST_LIKED",
    POST_COMMENTED = "POST_COMMENTED",
    NEW_POST = "NEW_POST",
    GENERAL = "GENERAL"
}